trigger:
- master

stages:
- stage: build_pipeline
  pool:
    vmImage: 'ubuntu-latest'


  jobs:
  - job:
    steps:

    - task: Docker@2
      displayName: Docker Build
      inputs:
        command: 'build'
        Dockerfile: 'Dockerfile'
        buildContext: '.'
        tags: |
          $(Build.BuildNumber)
          $(vOnBuildTag)

    - task: Docker@2
      displayName: Docker Push
      inputs:
        containerRegistry: 'azure-acr'
        repository: 'poclarabel01repo01'
        command: 'push'
        tags: |
          $(Build.BuildNumber)
          $(vOnBuildTag)

  
