trigger:
- master

stages:
- stage: build_pipeline
  pool:
    vmImage: 'Ubuntu 18.04'

  variables:
   imageName: 'poclarabel01repo01'

  jobs:
  - job:
    steps:

    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'azure-acr'
        repository: 'poclarabel01repo01'
        command: 'build'
        Dockerfile: 'Dockerfile'
        tags: '$(Build.BuildNumber)'

    - task: Docker@2
      displayName: Push image
      inputs:
        containerRegistry: 'azure-acr'
        repository: 'poclarabel01repo01'
        command: 'push'
        tags: '$(Build.BuildNumber)'

    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'TechLlamas (edea218b-98bf-47f0-83db-83085239f770)'
        appType: 'webAppContainer'
        WebAppName: 'poclarabel01webapp'
        DockerNamespace: 'poclarabel01acr01.azurecr.io'
        DockerRepository: 'poclarabel01repo01'
        DockerImageTag: '$(Build.BuildNumber)'
