trigger:
- master

stages:
- stage: build_pipeline
  pool:
    vmImage: 'Ubuntu 18.04'

  variables:
   imageName: 'poclarabel01repo01'
   phpVersion: 7.4

  jobs:
  - job:
    steps:

    - script: |
        sudo update-alternatives --set php /usr/bin/php$(phpVersion)
        sudo update-alternatives --set phar /usr/bin/phar$(phpVersion)
        sudo update-alternatives --set phpdbg /usr/bin/phpdbg$(phpVersion)
        sudo update-alternatives --set php-cgi /usr/bin/php-cgi$(phpVersion)
        sudo update-alternatives --set phar.phar /usr/bin/phar.phar$(phpVersion)
        php -version
      displayName: 'Use PHP version $(phpVersion)'

    - script: composer install --no-interaction --prefer-dist
      displayName: 'composer install'

    - script: phpunit
      displayName: 'Run tests with phpunit'
      continueOnError: false

    - task: PublishTestResults@2
      displayName: Publish unit test
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: 'tmp/TEST-Results.xml'
        testRunTitle: 'Publish Test results'

    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'azure-acr'
        repository: 'poclarabel01repo01'
        command: 'build'
        Dockerfile: 'Dockerfile'
        tags: '$(Build.BuildNumber)'

    - task: Docker@2
      displayName: Push image
      inputs:
        containerRegistry: 'azure-acr'
        repository: 'poclarabel01repo01'
        command: 'push'
        tags: '$(Build.BuildNumber)'

    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'TechLlamas (edea218b-98bf-47f0-83db-83085239f770)'
        appType: 'webAppContainer'
        WebAppName: 'poclarabel01webapp'
        DockerNamespace: 'poclarabel01acr01.azurecr.io'
        DockerRepository: 'poclarabel01repo01'
        DockerImageTag: '$(Build.BuildNumber)'
