trigger:
- master

stages:
- stage: build_pipeline
  pool:
    vmImage: 'ubuntu-latest'

  variables:
   imageName: 'poclarabel01repo01'


  jobs:
  - job:
    steps:

    - task: Docker@2
      displayName: Build an image
      inputs:
        repository: $(imageName)
        command: build
        Dockerfile: Dockerfile
        tags: |
          $(Build.BuildNumber)

    - task: Docker@2
      displayName: Docker Push
      inputs:
        repository: $(imageName)
        command: 'push'
