name: Laravel

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v2 

    - run: docker build . -t poclarabel01acr01.azurecr.io/poclarabel01repo01:latest
        
    - name: Container image scan
      uses: Azure/container-scan@v0
      with:
        image-name: poclarabel01acr01.azurecr.io/poclarabel01repo01:latest
        
    - uses: Azure/docker-login@v1
      with:
        login-server: poclarabel01acr01.azurecr.io
        username: poclarabel01acr01
        password: Z50Bev3AAZ8onXqMqAF4DENaIiwmc=05
    
    - name: Docker Push
    - run: docker push poclarabel01acr01.azurecr.io/poclarabel01repo01:latest

        
      
